apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  IPFS_NODE_HOST: http://ipfs-node.default.svc.cluster.local:5001
  NETWORK_URL: https://arb-rinkeby.g.alchemy.com/v2
  NODE_ENV: production
  QUEUE_MESSAGE: message
  QUEUE_TRANSCODE: transcode
  TEMP_PATH: ./tmp
